apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobboard-frontend
  labels:
    app: jobboard-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobboard-frontend
  template:
    metadata:
      labels:
        app: jobboard-frontend
    spec:
      containers:
      - name: frontend
        image: saikiranasamwar4/jobboard-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jobboard-frontend
  labels:
    app: jobboard-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: jobboard-frontend
